### ISSUE TITLE
Regular sensor for Mower Status

### ISSUE THREAD

**Issue by yeah** [yeah/home-assistant#1]
Introduce a regular sensor that only tracks the mower status, see https://community.home-assistant.io/t/husqvarna-automower-monitoring/4808/21?u=jansh

**Comment by hollie** [comment]
Hello @yeah,

just installed Home Assistant and as first interface towards actual hardware I installed your automower plugin. Thanks for the great work and for sharing.

I think having such 'regular sensor' would be big plus to see how the mower behaves regarding the weather timer that is present in certain models. 

I'm just getting my feet wet regarding Home Assistant, so adding this code myself will not be trivial :-) 

So a +1 for me on this ticket!

Best regards,
 Lieven.

**Comment by hollie** [comment]
Hi @yeah,

I've updated the code to the latest commits to your repo and I already see the complete mower status is reported when I click the 'vacuum' entry on the main screen. This is what I needed, so I don't know if it is still relevant to add another variable.

Best regards,
 Lieven. 
<img width="386" alt="schermafbeelding 2018-06-02 om 11 18 55" src="https://user-images.githubusercontent.com/697364/40872895-cc6562ba-6656-11e8-8800-0df494e64530.png">

**Comment by yeah** [comment]
I don't think we need this. It can be done using a [template sensor](https://community.home-assistant.io/t/husqvarna-automower-monitoring/4808/74?u=jansh).
